import { Market } from "./types";

export interface StockItem {
  ticker:   string;           // Yahoo Finance 용 (접미사 없음)
  name:     string;
  market:   Market;
  exchange?: "KS" | "KQ";    // 한국 주식 거래소 (KOSPI=KS, KOSDAQ=KQ)
}

// ── KOSPI / KOSDAQ 주요 종목 (500+)
export const KR_STOCKS: StockItem[] = [
  // ── 우선주 (고배당, 검색 최우선 노출) ─────────────────────────────────────
  { ticker: "005935", name: "삼성전자우",              market: "KR", exchange: "KS" },
  { ticker: "005385", name: "현대차우",               market: "KR", exchange: "KS" },
  { ticker: "005387", name: "현대차2우B",              market: "KR", exchange: "KS" },
  { ticker: "000215", name: "DL이앤씨우",              market: "KR", exchange: "KS" },
  { ticker: "051915", name: "LG화학우",               market: "KR", exchange: "KS" },
  { ticker: "000885", name: "한화우",                 market: "KR", exchange: "KS" },
  { ticker: "032835", name: "삼성생명우",              market: "KR", exchange: "KS" },
  { ticker: "009155", name: "삼성전기우",              market: "KR", exchange: "KS" },
  { ticker: "096775", name: "SK이노베이션우",           market: "KR", exchange: "KS" },
  { ticker: "138041", name: "메리츠금융지주우",          market: "KR", exchange: "KS" },
  { ticker: "006405", name: "삼성SDI우",              market: "KR", exchange: "KS" },
  { ticker: "000070", name: "하이트진로우",             market: "KR", exchange: "KS" },
  { ticker: "000725", name: "현대건설우",              market: "KR", exchange: "KS" },
  { ticker: "003555", name: "LG우",                  market: "KR", exchange: "KS" },
  { ticker: "003547", name: "대웅제약우",              market: "KR", exchange: "KS" },
  { ticker: "001465", name: "현대해상우",              market: "KR", exchange: "KS" },
  { ticker: "007575", name: "이수화학우",              market: "KR", exchange: "KS" },
  { ticker: "004545", name: "삼양사우",               market: "KR", exchange: "KS" },
  { ticker: "078935", name: "GS우",                  market: "KR", exchange: "KS" },
  { ticker: "004835", name: "효성우",                 market: "KR", exchange: "KS" },
  { ticker: "003605", name: "SK케미칼우",              market: "KR", exchange: "KS" },
  { ticker: "000155", name: "두산우",                 market: "KR", exchange: "KS" },
  { ticker: "001515", name: "SK우",                  market: "KR", exchange: "KS" },
  { ticker: "033780", name: "KT&G",                  market: "KR", exchange: "KS" },
  // 반도체/전자
  { ticker: "005930", name: "삼성전자",              market: "KR", exchange: "KS" },
  { ticker: "000660", name: "SK하이닉스",             market: "KR", exchange: "KS" },
  { ticker: "009150", name: "삼성전기",               market: "KR", exchange: "KS" },
  { ticker: "011070", name: "LG이노텍",               market: "KR", exchange: "KS" },
  { ticker: "066570", name: "LG전자",                 market: "KR", exchange: "KS" },
  { ticker: "010140", name: "삼성중공업",              market: "KR", exchange: "KS" },
  { ticker: "042700", name: "한미반도체",              market: "KR", exchange: "KQ" },
  { ticker: "000990", name: "DB하이텍",               market: "KR", exchange: "KS" },
  { ticker: "336370", name: "솔브레인홀딩스",           market: "KR", exchange: "KQ" },
  { ticker: "240810", name: "원익IPS",                market: "KR", exchange: "KQ" },
  { ticker: "089890", name: "이오테크닉스",             market: "KR", exchange: "KQ" },
  { ticker: "131970", name: "테스",                   market: "KR", exchange: "KQ" },
  { ticker: "084370", name: "유진테크",               market: "KR", exchange: "KQ" },
  { ticker: "213420", name: "덕산네오룩스",             market: "KR", exchange: "KQ" },
  { ticker: "122830", name: "원익머트리얼즈",           market: "KR", exchange: "KQ" },
  { ticker: "036540", name: "SFA반도체",              market: "KR", exchange: "KQ" },
  { ticker: "048260", name: "오스코텍",               market: "KR", exchange: "KQ" },
  // 금융/은행
  { ticker: "105560", name: "KB금융",                 market: "KR" },
  { ticker: "055550", name: "신한지주",                market: "KR" },
  { ticker: "086790", name: "하나금융지주",             market: "KR" },
  { ticker: "316140", name: "우리금융지주",             market: "KR" },
  { ticker: "024110", name: "기업은행",                market: "KR" },
  { ticker: "138930", name: "BNK금융지주",             market: "KR" },
  { ticker: "139130", name: "DGB금융지주",             market: "KR" },
  { ticker: "175330", name: "JB금융지주",              market: "KR" },
  { ticker: "138040", name: "메리츠금융지주",           market: "KR" },
  { ticker: "323410", name: "카카오뱅크",              market: "KR" },
  { ticker: "377300", name: "카카오페이",              market: "KR" },
  { ticker: "039490", name: "키움증권",               market: "KR" },
  { ticker: "037620", name: "미래에셋증권",             market: "KR" },
  { ticker: "016360", name: "삼성증권",               market: "KR" },
  { ticker: "005940", name: "NH투자증권",              market: "KR" },
  { ticker: "003470", name: "유안타증권",              market: "KR" },
  { ticker: "078020", name: "이베스트투자증권",          market: "KR" },
  { ticker: "030610", name: "교보증권",               market: "KR" },
  { ticker: "003540", name: "대신증권",               market: "KR" },
  { ticker: "001500", name: "현대차증권",              market: "KR" },
  { ticker: "039670", name: "한화투자증권",             market: "KR" },
  // 보험
  { ticker: "032830", name: "삼성생명",               market: "KR" },
  { ticker: "088350", name: "한화생명",               market: "KR" },
  { ticker: "005830", name: "DB손해보험",              market: "KR" },
  { ticker: "000810", name: "삼성화재",               market: "KR" },
  { ticker: "001450", name: "현대해상",               market: "KR" },
  { ticker: "000060", name: "메리츠화재",              market: "KR" },
  { ticker: "082920", name: "비엔케이캐피탈",           market: "KR" },
  // 통신
  { ticker: "017670", name: "SK텔레콤",               market: "KR" },
  { ticker: "030200", name: "KT",                    market: "KR" },
  { ticker: "032640", name: "LG유플러스",              market: "KR" },
  // 자동차
  { ticker: "005380", name: "현대차",                 market: "KR" },
  { ticker: "000270", name: "기아",                   market: "KR" },
  { ticker: "012330", name: "현대모비스",              market: "KR" },
  { ticker: "161390", name: "한국타이어앤테크놀로지",   market: "KR" },
  { ticker: "002390", name: "넥센타이어",              market: "KR" },
  { ticker: "004020", name: "현대제철",               market: "KR" },
  { ticker: "018880", name: "한온시스템",              market: "KR" },
  { ticker: "010620", name: "현대미포조선",             market: "KR" },
  { ticker: "007340", name: "현대엘리베이터",           market: "KR" },
  { ticker: "007570", name: "일양약품",               market: "KR" },
  // IT/플랫폼
  { ticker: "035420", name: "NAVER",                 market: "KR" },
  { ticker: "035420", name: "네이버",                 market: "KR" },
  { ticker: "035720", name: "카카오",                 market: "KR" },
  { ticker: "259960", name: "크래프톤",               market: "KR" },
  { ticker: "036570", name: "엔씨소프트",              market: "KR" },
  { ticker: "251270", name: "넷마블",                 market: "KR" },
  { ticker: "263750", name: "펄어비스",               market: "KR" },
  { ticker: "095660", name: "네오위즈",               market: "KR" },
  { ticker: "078340", name: "컴투스",                 market: "KR" },
  { ticker: "225570", name: "넥슨게임즈",              market: "KR" },
  { ticker: "192080", name: "더블유게임즈",             market: "KR" },
  { ticker: "041920", name: "메가스터디",              market: "KR" },
  { ticker: "064260", name: "다날",                   market: "KR" },
  // 에너지/정유
  { ticker: "010950", name: "S-Oil",                 market: "KR" },
  { ticker: "096770", name: "SK이노베이션",             market: "KR" },
  { ticker: "078930", name: "GS",                    market: "KR" },
  { ticker: "015760", name: "한국전력",               market: "KR" },
  { ticker: "036460", name: "한국가스공사",             market: "KR" },
  { ticker: "088980", name: "맥쿼리인프라",             market: "KR" },
  { ticker: "117580", name: "대성에너지",              market: "KR" },
  { ticker: "034590", name: "인천도시가스",             market: "KR" },
  { ticker: "071050", name: "한국가스기술공사",          market: "KR" },
  // 철강/소재/화학
  { ticker: "005490", name: "POSCO홀딩스",            market: "KR" },
  { ticker: "005490", name: "포스코홀딩스",            market: "KR" },
  { ticker: "010130", name: "고려아연",               market: "KR" },
  { ticker: "000670", name: "영풍",                   market: "KR" },
  { ticker: "002380", name: "KCC",                   market: "KR" },
  { ticker: "073240", name: "금호석유",               market: "KR" },
  { ticker: "051910", name: "LG화학",                 market: "KR" },
  { ticker: "006400", name: "삼성SDI",                market: "KR" },
  { ticker: "011170", name: "롯데케미칼",              market: "KR" },
  { ticker: "047050", name: "포스코인터내셔널",         market: "KR" },
  { ticker: "001230", name: "동국제강",               market: "KR" },
  { ticker: "009420", name: "한화솔루션",              market: "KR" },
  { ticker: "011790", name: "SKC",                   market: "KR" },
  { ticker: "120110", name: "코오롱인더",              market: "KR" },
  { ticker: "014680", name: "한솔케미칼",              market: "KR" },
  { ticker: "298000", name: "효성화학",               market: "KR" },
  { ticker: "010060", name: "OCI홀딩스",              market: "KR" },
  { ticker: "004000", name: "롯데정밀화학",             market: "KR" },
  { ticker: "002350", name: "넥스틸",                 market: "KR" },
  { ticker: "017890", name: "세아제강지주",             market: "KR" },
  { ticker: "306200", name: "세아베스틸지주",           market: "KR" },
  { ticker: "014830", name: "동일방직",               market: "KR" },
  { ticker: "024090", name: "DN오토모티브",             market: "KR" },
  { ticker: "004985", name: "테이팩스",               market: "KR" },
  // 지주사
  { ticker: "034730", name: "SK",                    market: "KR" },
  { ticker: "003550", name: "LG",                    market: "KR" },
  { ticker: "000150", name: "두산",                   market: "KR" },
  { ticker: "000880", name: "한화",                   market: "KR" },
  { ticker: "001040", name: "CJ",                    market: "KR" },
  { ticker: "006260", name: "LS",                    market: "KR" },
  { ticker: "028260", name: "삼성물산",               market: "KR" },
  { ticker: "267250", name: "HD현대",                 market: "KR" },
  { ticker: "004800", name: "효성",                   market: "KR" },
  { ticker: "000100", name: "유한양행",               market: "KR" },
  { ticker: "002210", name: "동성제약",               market: "KR" },
  { ticker: "001120", name: "LX홀딩스",               market: "KR" },
  { ticker: "079550", name: "LIG넥스원",              market: "KR" },
  { ticker: "071840", name: "하이트진로홀딩스",          market: "KR" },
  // 바이오/제약
  { ticker: "207940", name: "삼성바이오로직스",         market: "KR" },
  { ticker: "068270", name: "셀트리온",               market: "KR" },
  { ticker: "128940", name: "한미약품",               market: "KR" },
  { ticker: "185750", name: "종근당",                 market: "KR" },
  { ticker: "003090", name: "대웅",                   market: "KR" },
  { ticker: "069620", name: "대웅제약",               market: "KR" },
  { ticker: "000220", name: "유유제약",               market: "KR" },
  { ticker: "001060", name: "JW중외제약",              market: "KR" },
  { ticker: "002630", name: "오리엔트바이오",           market: "KR" },
  { ticker: "145020", name: "휴젤",                   market: "KR" },
  { ticker: "012800", name: "동진쎄미켐",              market: "KR" },
  { ticker: "170900", name: "동아에스티",              market: "KR" },
  { ticker: "009420", name: "한화솔루션",              market: "KR" },
  { ticker: "003520", name: "동아쏘시오홀딩스",          market: "KR" },
  // 유통/식품/음료
  { ticker: "282330", name: "BGF리테일",              market: "KR" },
  { ticker: "007070", name: "GS리테일",               market: "KR" },
  { ticker: "139480", name: "이마트",                 market: "KR" },
  { ticker: "023530", name: "롯데쇼핑",               market: "KR" },
  { ticker: "097950", name: "CJ제일제당",              market: "KR" },
  { ticker: "001680", name: "대상",                   market: "KR" },
  { ticker: "000080", name: "하이트진로",              market: "KR" },
  { ticker: "004170", name: "신세계",                 market: "KR" },
  { ticker: "069960", name: "현대백화점",              market: "KR" },
  { ticker: "271560", name: "오리온",                 market: "KR" },
  { ticker: "002790", name: "아모레퍼시픽",            market: "KR" },
  { ticker: "051900", name: "LG생활건강",              market: "KR" },
  { ticker: "005180", name: "빙그레",                 market: "KR" },
  { ticker: "008350", name: "남양유업",               market: "KR" },
  { ticker: "004830", name: "덴티움",                 market: "KR" },
  { ticker: "003230", name: "삼양식품",               market: "KR" },
  { ticker: "005610", name: "SPC삼립",                market: "KR" },
  { ticker: "004990", name: "롯데제과",               market: "KR" },
  { ticker: "007030", name: "계열",                  market: "KR" },
  { ticker: "003580", name: "HLB생명과학",             market: "KR" },
  { ticker: "006120", name: "SK디스커버리",             market: "KR" },
  // 건설
  { ticker: "000720", name: "현대건설",               market: "KR" },
  { ticker: "375500", name: "DL이앤씨",               market: "KR" },
  { ticker: "006360", name: "GS건설",                 market: "KR" },
  { ticker: "047040", name: "대우건설",               market: "KR" },
  { ticker: "294870", name: "HDC현대산업개발",          market: "KR" },
  { ticker: "009410", name: "태영건설",               market: "KR" },
  { ticker: "013580", name: "계룡건설산업",             market: "KR" },
  { ticker: "002990", name: "금호건설",               market: "KR" },
  { ticker: "003070", name: "코오롱글로벌",             market: "KR" },
  { ticker: "004960", name: "한신공영",               market: "KR" },
  { ticker: "005960", name: "동부건설",               market: "KR" },
  { ticker: "082640", name: "동양건설산업",             market: "KR" },
  { ticker: "034300", name: "신세계건설",              market: "KR" },
  { ticker: "023000", name: "삼원강재",               market: "KR" },
  { ticker: "097230", name: "한진중공업",              market: "KR" },
  { ticker: "025700", name: "롯데건설",               market: "KR" },
  { ticker: "003800", name: "에이스침대",              market: "KR" },
  { ticker: "006840", name: "일신방직",               market: "KR" },
  { ticker: "000210", name: "DL",                    market: "KR" },
  { ticker: "001680", name: "대상",                   market: "KR" },
  { ticker: "023760", name: "한국경제TV",              market: "KR" },
  { ticker: "008830", name: "대동기어",               market: "KR" },
  { ticker: "021320", name: "KCC건설",                market: "KR" },
  { ticker: "012650", name: "삼성제약",               market: "KR" },
  { ticker: "014440", name: "영보화학",               market: "KR" },
  { ticker: "067290", name: "이노션",                 market: "KR" },
  // 방산/조선/중공업
  { ticker: "047810", name: "한국항공우주",             market: "KR" },
  { ticker: "009540", name: "HD한국조선해양",           market: "KR" },
  { ticker: "042660", name: "한화오션",               market: "KR" },
  { ticker: "064350", name: "현대로템",               market: "KR" },
  { ticker: "329180", name: "HD현대중공업",            market: "KR" },
  { ticker: "012450", name: "한화에어로스페이스",        market: "KR" },
  { ticker: "034020", name: "두산에너빌리티",           market: "KR" },
  { ticker: "267260", name: "HD현대일렉트릭",           market: "KR" },
  { ticker: "082740", name: "HSD엔진",                market: "KR" },
  { ticker: "010690", name: "화신",                   market: "KR" },
  { ticker: "003090", name: "대웅",                   market: "KR" },
  // 항공/운송/물류
  { ticker: "003490", name: "대한항공",               market: "KR" },
  { ticker: "180640", name: "한진칼",                 market: "KR" },
  { ticker: "272450", name: "진에어",                 market: "KR" },
  { ticker: "089590", name: "제주항공",               market: "KR" },
  { ticker: "020560", name: "아시아나항공",             market: "KR" },
  { ticker: "011200", name: "HMM",                   market: "KR" },
  { ticker: "028670", name: "팬오션",                 market: "KR" },
  { ticker: "000700", name: "유수홀딩스",              market: "KR" },
  { ticker: "002340", name: "한진",                   market: "KR" },
  { ticker: "004870", name: "티웨이항공",              market: "KR" },
  { ticker: "005380", name: "현대차",                 market: "KR" },
  // 엔터/레저/미디어
  { ticker: "035250", name: "강원랜드",               market: "KR" },
  { ticker: "034230", name: "파라다이스",              market: "KR" },
  { ticker: "352820", name: "하이브",                 market: "KR" },
  { ticker: "041510", name: "SM엔터테인먼트",           market: "KR" },
  { ticker: "035900", name: "JYP엔터테인먼트",          market: "KR" },
  { ticker: "122870", name: "YG엔터테인먼트",           market: "KR" },
  { ticker: "036270", name: "YG PLUS",               market: "KR" },
  { ticker: "007660", name: "이수페타시스",             market: "KR" },
  { ticker: "052690", name: "한전기술",               market: "KR" },
  { ticker: "053210", name: "스카이라이프",             market: "KR" },
  { ticker: "036420", name: "제이콘텐트리",             market: "KR" },
  { ticker: "016890", name: "전방",                   market: "KR" },
  // 부동산/리츠
  { ticker: "088980", name: "맥쿼리인프라",             market: "KR" },
  { ticker: "395400", name: "SK리츠",                 market: "KR" },
  { ticker: "432320", name: "KB스타리츠",              market: "KR" },
  { ticker: "448730", name: "한화리츠",               market: "KR" },
  { ticker: "330590", name: "롯데리츠",               market: "KR" },
  { ticker: "293940", name: "신한알파리츠",             market: "KR" },
  { ticker: "357430", name: "디앤디플랫폼리츠",          market: "KR" },
  { ticker: "334890", name: "이지스밸류리츠",           market: "KR" },
  // KOSDAQ 주요
  { ticker: "277810", name: "레인보우로보틱스",          market: "KR" },
  { ticker: "066970", name: "엘엔에프",               market: "KR" },
  { ticker: "214450", name: "파마리서치",              market: "KR" },
  { ticker: "248070", name: "솔루엠",                 market: "KR" },
  { ticker: "141080", name: "리가켐바이오",             market: "KR" },
  { ticker: "237690", name: "에스티팜",               market: "KR" },
  { ticker: "272290", name: "이녹스첨단소재",           market: "KR" },
  { ticker: "090460", name: "비에이치",               market: "KR" },
  { ticker: "241710", name: "코스메카코리아",           market: "KR" },
  { ticker: "204270", name: "제이앤티씨",              market: "KR" },
  { ticker: "108860", name: "셀바스AI",               market: "KR" },
  { ticker: "031980", name: "피에스케이홀딩스",          market: "KR" },
  { ticker: "054080", name: "에이피시스템",             market: "KR" },
  { ticker: "192820", name: "코스맥스",               market: "KR" },
  { ticker: "084110", name: "휴온스글로벌",             market: "KR" },
  { ticker: "234080", name: "JW생명과학",              market: "KR" },
  { ticker: "064760", name: "씨에스윈드",              market: "KR" },
  { ticker: "145090", name: "비에스한일시멘트",          market: "KR" },
  { ticker: "285130", name: "SK바이오팜",              market: "KR" },
  { ticker: "039200", name: "오스코텍",               market: "KR" },
  { ticker: "203690", name: "스피어파워",              market: "KR" },
  { ticker: "050890", name: "쏠리드",                 market: "KR" },
  { ticker: "123410", name: "코리아에프티",             market: "KR" },
  { ticker: "086520", name: "에코프로",               market: "KR" },
  { ticker: "247540", name: "에코프로비엠",             market: "KR" },
  { ticker: "373220", name: "LG에너지솔루션",           market: "KR" },
  { ticker: "091990", name: "셀트리온헬스케어",          market: "KR" },
  { ticker: "196170", name: "알테오젠",               market: "KR" },
  { ticker: "028300", name: "HLB",                   market: "KR" },
  { ticker: "293490", name: "카카오게임즈",             market: "KR" },
  { ticker: "058470", name: "리노공업",               market: "KR" },
  { ticker: "214150", name: "클래시스",               market: "KR" },
  { ticker: "403870", name: "HPSP",                  market: "KR" },
  { ticker: "357780", name: "솔브레인",               market: "KR" },
  { ticker: "036800", name: "나스미디어",              market: "KR" },
  { ticker: "112040", name: "위메이드",               market: "KR" },
  { ticker: "039030", name: "이오테크닉스",             market: "KR" },
  { ticker: "036810", name: "에프에스티",              market: "KR" },
  { ticker: "054040", name: "한국전자인증",             market: "KR" },
  { ticker: "045660", name: "에이텍",                 market: "KR" },
  { ticker: "033100", name: "이엘피",                 market: "KR" },
  { ticker: "067170", name: "누리플렉스",              market: "KR" },
  { ticker: "064760", name: "씨에스윈드",              market: "KR" },
  { ticker: "263720", name: "디앤씨미디어",             market: "KR" },
  { ticker: "023160", name: "태광",                   market: "KR" },
  { ticker: "072770", name: "율호",                   market: "KR" },
  { ticker: "900140", name: "엘브이엠씨홀딩스",          market: "KR" },
  { ticker: "006650", name: "대한유화",               market: "KR" },
  { ticker: "010780", name: "아이에스동서",             market: "KR" },
  { ticker: "008490", name: "서흥",                   market: "KR" },
  // 기타/중소형
  { ticker: "001740", name: "SK네트웍스",              market: "KR" },
  { ticker: "001230", name: "동국제강",               market: "KR" },
  { ticker: "025540", name: "한국단자공업",             market: "KR" },
  { ticker: "007590", name: "동방아그로",              market: "KR" },
  { ticker: "016880", name: "웰투시인베스트먼트",        market: "KR" },
  { ticker: "001560", name: "제일연마",               market: "KR", exchange: "KS" },
  { ticker: "001560", name: "제일연마",               market: "KR" },
  { ticker: "006740", name: "영풍제지",               market: "KR" },
  { ticker: "004150", name: "한솔홀딩스",              market: "KR" },
  { ticker: "001450", name: "현대해상",               market: "KR" },
  { ticker: "002720", name: "국제약품",               market: "KR" },
  { ticker: "033180", name: "웰크론",                 market: "KR" },
  { ticker: "009290", name: "광주신세계",              market: "KR" },
  { ticker: "200350", name: "래몽래인",               market: "KR" },
  { ticker: "020120", name: "NH스팩17호",              market: "KR" },
  { ticker: "003600", name: "SK케미칼",               market: "KR" },
  { ticker: "007570", name: "일양약품",               market: "KR" },
  { ticker: "002300", name: "한진칼",                 market: "KR" },
  { ticker: "016360", name: "삼성증권",               market: "KR" },
  { ticker: "071050", name: "한국가스기술공사",          market: "KR" },
  { ticker: "192400", name: "쿠쿠홀딩스",              market: "KR" },
  { ticker: "284740", name: "쿠쿠홈시스",              market: "KR" },
  { ticker: "006840", name: "일신방직",               market: "KR" },
  { ticker: "003620", name: "쌍용C&E",                market: "KR" },
  { ticker: "003410", name: "쌍용양회공업",             market: "KR" },
  { ticker: "009450", name: "경동나비엔",              market: "KR" },
  { ticker: "010140", name: "삼성중공업",              market: "KR" },
  { ticker: "078000", name: "텔코웨어",               market: "KR" },
  { ticker: "002450", name: "한국투자금융지주",          market: "KR" },
  { ticker: "005440", name: "현대지에프홀딩스",          market: "KR" },
  { ticker: "005010", name: "휴스틸",                 market: "KR" },
  { ticker: "004440", name: "한국철강",               market: "KR" },
  { ticker: "023530", name: "롯데쇼핑",               market: "KR" },
  { ticker: "006400", name: "삼성SDI",                market: "KR" },
  { ticker: "307950", name: "현대오토에버",             market: "KR" },
  { ticker: "071970", name: "STX중공업",              market: "KR" },
  { ticker: "003160", name: "디아이씨",               market: "KR" },
  { ticker: "025560", name: "미래산업",               market: "KR" },
  { ticker: "088130", name: "동아엘텍",               market: "KR" },
  { ticker: "083500", name: "에프엔에스테크",           market: "KR" },
  { ticker: "032190", name: "다우기술",               market: "KR" },
  { ticker: "013520", name: "화승엔터프라이즈",          market: "KR" },
  { ticker: "013360", name: "일진머티리얼즈",           market: "KR" },
  { ticker: "002820", name: "SH에너지화학",            market: "KR" },
  { ticker: "011160", name: "정한",                   market: "KR" },
  { ticker: "051600", name: "한전KPS",                market: "KR" },
  { ticker: "016250", name: "전기초자",               market: "KR" },
  { ticker: "100250", name: "진양홀딩스",              market: "KR" },
  { ticker: "014680", name: "한솔케미칼",              market: "KR" },
  { ticker: "011200", name: "HMM",                   market: "KR" },
  { ticker: "001300", name: "크라운해태홀딩스",          market: "KR" },
  { ticker: "025900", name: "동화기업",               market: "KR" },
  { ticker: "007720", name: "성신양회",               market: "KR" },
  { ticker: "040420", name: "정상제이엘에스",           market: "KR" },
  { ticker: "060310", name: "3S",                    market: "KR" },
];

// ── 미국 주요 종목 (S&P500 + 고배당 + 인기 종목 150+)
export const US_STOCKS: StockItem[] = [
  // 빅테크
  { ticker: "AAPL",  name: "Apple",                         market: "US" },
  { ticker: "MSFT",  name: "Microsoft",                     market: "US" },
  { ticker: "GOOGL", name: "Alphabet (Google)",              market: "US" },
  { ticker: "AMZN",  name: "Amazon",                        market: "US" },
  { ticker: "NVDA",  name: "NVIDIA",                        market: "US" },
  { ticker: "META",  name: "Meta (Facebook)",               market: "US" },
  { ticker: "TSLA",  name: "Tesla",                         market: "US" },
  // 통신
  { ticker: "T",     name: "AT&T",                          market: "US" },
  { ticker: "VZ",    name: "Verizon",                       market: "US" },
  // 담배
  { ticker: "MO",    name: "Altria Group",                  market: "US" },
  { ticker: "PM",    name: "Philip Morris",                 market: "US" },
  { ticker: "BTI",   name: "British American Tobacco",      market: "US" },
  // REIT
  { ticker: "O",     name: "Realty Income",                 market: "US" },
  { ticker: "WPC",   name: "W. P. Carey",                   market: "US" },
  { ticker: "STAG",  name: "STAG Industrial",               market: "US" },
  { ticker: "NLY",   name: "Annaly Capital",                market: "US" },
  { ticker: "AGNC",  name: "AGNC Investment",               market: "US" },
  { ticker: "MPW",   name: "Medical Properties Trust",      market: "US" },
  { ticker: "AMT",   name: "American Tower",                market: "US" },
  { ticker: "PLD",   name: "Prologis",                      market: "US" },
  { ticker: "SPG",   name: "Simon Property Group",          market: "US" },
  // 고배당 ETF
  { ticker: "JEPI",  name: "JPMorgan Equity Premium Income ETF", market: "US" },
  { ticker: "JEPQ",  name: "JPMorgan Nasdaq Equity Premium ETF", market: "US" },
  { ticker: "SCHD",  name: "Schwab US Dividend ETF",        market: "US" },
  { ticker: "HDV",   name: "iShares Core High Dividend ETF", market: "US" },
  { ticker: "SPYD",  name: "SPDR S&P 500 High Dividend ETF", market: "US" },
  { ticker: "DVY",   name: "iShares Select Dividend ETF",   market: "US" },
  { ticker: "VYM",   name: "Vanguard High Dividend Yield ETF", market: "US" },
  { ticker: "QYLD",  name: "Global X NASDAQ-100 Covered Call ETF", market: "US" },
  { ticker: "XYLD",  name: "Global X S&P 500 Covered Call ETF", market: "US" },
  { ticker: "RYLD",  name: "Global X Russell 2000 Covered Call ETF", market: "US" },
  // 소비재
  { ticker: "KO",    name: "Coca-Cola",                     market: "US" },
  { ticker: "PEP",   name: "PepsiCo",                       market: "US" },
  { ticker: "GIS",   name: "General Mills",                 market: "US" },
  { ticker: "CAG",   name: "ConAgra Brands",                market: "US" },
  { ticker: "MCD",   name: "McDonald's",                    market: "US" },
  { ticker: "TGT",   name: "Target",                        market: "US" },
  { ticker: "WMT",   name: "Walmart",                       market: "US" },
  { ticker: "COST",  name: "Costco",                        market: "US" },
  { ticker: "HD",    name: "Home Depot",                    market: "US" },
  { ticker: "LOW",   name: "Lowe's",                        market: "US" },
  { ticker: "NKE",   name: "Nike",                          market: "US" },
  { ticker: "SBUX",  name: "Starbucks",                     market: "US" },
  { ticker: "YUM",   name: "Yum! Brands",                   market: "US" },
  { ticker: "HSY",   name: "Hershey",                       market: "US" },
  { ticker: "CPB",   name: "Campbell Soup",                 market: "US" },
  { ticker: "CLX",   name: "Clorox",                        market: "US" },
  { ticker: "KMB",   name: "Kimberly-Clark",                market: "US" },
  { ticker: "PG",    name: "Procter & Gamble",              market: "US" },
  { ticker: "CL",    name: "Colgate-Palmolive",             market: "US" },
  // 헬스케어/제약
  { ticker: "JNJ",   name: "Johnson & Johnson",             market: "US" },
  { ticker: "ABBV",  name: "AbbVie",                        market: "US" },
  { ticker: "PFE",   name: "Pfizer",                        market: "US" },
  { ticker: "BMY",   name: "Bristol-Myers Squibb",          market: "US" },
  { ticker: "MRK",   name: "Merck",                         market: "US" },
  { ticker: "AMGN",  name: "Amgen",                         market: "US" },
  { ticker: "GILD",  name: "Gilead Sciences",               market: "US" },
  { ticker: "CVS",   name: "CVS Health",                    market: "US" },
  { ticker: "UNH",   name: "UnitedHealth",                  market: "US" },
  { ticker: "ELV",   name: "Elevance Health",               market: "US" },
  { ticker: "ABT",   name: "Abbott Laboratories",           market: "US" },
  { ticker: "MDT",   name: "Medtronic",                     market: "US" },
  // 기술
  { ticker: "IBM",   name: "IBM",                           market: "US" },
  { ticker: "INTC",  name: "Intel",                         market: "US" },
  { ticker: "TXN",   name: "Texas Instruments",             market: "US" },
  { ticker: "QCOM",  name: "Qualcomm",                      market: "US" },
  { ticker: "AVGO",  name: "Broadcom",                      market: "US" },
  { ticker: "STX",   name: "Seagate Technology",            market: "US" },
  { ticker: "CSCO",  name: "Cisco",                         market: "US" },
  { ticker: "ORCL",  name: "Oracle",                        market: "US" },
  { ticker: "ACN",   name: "Accenture",                     market: "US" },
  // 에너지
  { ticker: "XOM",   name: "ExxonMobil",                    market: "US" },
  { ticker: "CVX",   name: "Chevron",                       market: "US" },
  { ticker: "EPD",   name: "Enterprise Products Partners",  market: "US" },
  { ticker: "ET",    name: "Energy Transfer",               market: "US" },
  { ticker: "OKE",   name: "ONEOK",                         market: "US" },
  { ticker: "ENB",   name: "Enbridge",                      market: "US" },
  { ticker: "MPC",   name: "Marathon Petroleum",            market: "US" },
  { ticker: "PSX",   name: "Phillips 66",                   market: "US" },
  { ticker: "VLO",   name: "Valero Energy",                 market: "US" },
  { ticker: "COP",   name: "ConocoPhillips",                market: "US" },
  { ticker: "SLB",   name: "Schlumberger",                  market: "US" },
  // 산업/소재
  { ticker: "MMM",   name: "3M",                            market: "US" },
  { ticker: "LYB",   name: "LyondellBasell",                market: "US" },
  { ticker: "DOW",   name: "Dow Inc",                       market: "US" },
  { ticker: "CAT",   name: "Caterpillar",                   market: "US" },
  { ticker: "EMR",   name: "Emerson Electric",              market: "US" },
  { ticker: "HON",   name: "Honeywell",                     market: "US" },
  { ticker: "GE",    name: "GE Aerospace",                  market: "US" },
  { ticker: "UPS",   name: "UPS",                           market: "US" },
  { ticker: "FDX",   name: "FedEx",                         market: "US" },
  { ticker: "BA",    name: "Boeing",                        market: "US" },
  { ticker: "LMT",   name: "Lockheed Martin",               market: "US" },
  { ticker: "RTX",   name: "RTX (Raytheon)",                market: "US" },
  // 금융
  { ticker: "JPM",   name: "JPMorgan Chase",                market: "US" },
  { ticker: "BAC",   name: "Bank of America",               market: "US" },
  { ticker: "WFC",   name: "Wells Fargo",                   market: "US" },
  { ticker: "C",     name: "Citigroup",                     market: "US" },
  { ticker: "GS",    name: "Goldman Sachs",                 market: "US" },
  { ticker: "MS",    name: "Morgan Stanley",                market: "US" },
  { ticker: "AXP",   name: "American Express",              market: "US" },
  { ticker: "V",     name: "Visa",                          market: "US" },
  { ticker: "MA",    name: "Mastercard",                    market: "US" },
  { ticker: "BLK",   name: "BlackRock",                     market: "US" },
  { ticker: "MAIN",  name: "Main Street Capital",           market: "US" },
  { ticker: "ARCC",  name: "Ares Capital",                  market: "US" },
  // 유틸리티
  { ticker: "D",     name: "Dominion Energy",               market: "US" },
  { ticker: "NEE",   name: "NextEra Energy",                market: "US" },
  { ticker: "ED",    name: "Consolidated Edison",           market: "US" },
  { ticker: "SO",    name: "Southern Company",              market: "US" },
  { ticker: "DUK",   name: "Duke Energy",                   market: "US" },
  { ticker: "WEC",   name: "WEC Energy Group",              market: "US" },
  { ticker: "AEP",   name: "American Electric Power",       market: "US" },
  { ticker: "EXC",   name: "Exelon",                        market: "US" },
  // 자동차
  { ticker: "F",     name: "Ford Motor",                    market: "US" },
  { ticker: "GM",    name: "General Motors",                market: "US" },
  // 광업
  { ticker: "RIO",   name: "Rio Tinto",                     market: "US" },
  { ticker: "FCX",   name: "Freeport-McMoRan",              market: "US" },
  { ticker: "NEM",   name: "Newmont",                       market: "US" },
];

/** 관련성 기준으로 정렬된 검색 결과 반환 */
export function searchStocks(query: string, market: Market): StockItem[] {
  const q    = query.trim().toLowerCase();
  if (!q)    return [];

  const list = market === "KR" ? KR_STOCKS : US_STOCKS;

  const seen    = new Set<string>();
  const results = list.filter((s) => {
    if (seen.has(s.ticker)) return false; // 중복 제거
    const nameMatch   = s.name.toLowerCase().includes(q);
    const tickerMatch = s.ticker.toLowerCase().includes(q);
    if (nameMatch || tickerMatch) { seen.add(s.ticker); return true; }
    return false;
  });

  // 관련성 정렬: 시작 일치 > 포함
  results.sort((a, b) => {
    const aName = a.name.toLowerCase();
    const bName = b.name.toLowerCase();
    const aScore = aName === q ? 0 : aName.startsWith(q) ? 1 : 2;
    const bScore = bName === q ? 0 : bName.startsWith(q) ? 1 : 2;
    return aScore - bScore;
  });

  return results.slice(0, 20);
}
