import { Market } from "./types";

export interface TickerItem {
  ticker: string;
  name: string;
  market: Market;
}

export const KR_TICKERS: TickerItem[] = [
  { ticker: "105560", name: "KB금융",           market: "KR" },
  { ticker: "055550", name: "신한지주",          market: "KR" },
  { ticker: "086790", name: "하나금융지주",       market: "KR" },
  { ticker: "316140", name: "우리금융지주",       market: "KR" },
  { ticker: "024110", name: "기업은행",          market: "KR" },
  { ticker: "138930", name: "BNK금융지주",       market: "KR" },
  { ticker: "139130", name: "DGB금융지주",       market: "KR" },
  { ticker: "175330", name: "JB금융지주",        market: "KR" },
  { ticker: "138040", name: "메리츠금융지주",     market: "KR" },
  { ticker: "032830", name: "삼성생명",          market: "KR" },
  { ticker: "088350", name: "한화생명",          market: "KR" },
  { ticker: "005830", name: "DB손해보험",        market: "KR" },
  { ticker: "000810", name: "삼성화재",          market: "KR" },
  { ticker: "001450", name: "현대해상",          market: "KR" },
  { ticker: "000060", name: "메리츠화재",        market: "KR" },
  { ticker: "017670", name: "SK텔레콤",         market: "KR" },
  { ticker: "030200", name: "KT",              market: "KR" },
  { ticker: "032640", name: "LG유플러스",        market: "KR" },
  { ticker: "033780", name: "KT&G",            market: "KR" },
  { ticker: "088980", name: "맥쿼리인프라",      market: "KR" },
  { ticker: "015760", name: "한국전력",          market: "KR" },
  { ticker: "036460", name: "한국가스공사",       market: "KR" },
  { ticker: "010950", name: "S-Oil",           market: "KR" },
  { ticker: "096770", name: "SK이노베이션",      market: "KR" },
  { ticker: "078930", name: "GS",              market: "KR" },
  { ticker: "005490", name: "POSCO홀딩스",      market: "KR" },
  { ticker: "010130", name: "고려아연",          market: "KR" },
  { ticker: "002380", name: "KCC",             market: "KR" },
  { ticker: "073240", name: "금호석유",          market: "KR" },
  { ticker: "000270", name: "기아",             market: "KR" },
  { ticker: "005380", name: "현대차",            market: "KR" },
  { ticker: "012330", name: "현대모비스",        market: "KR" },
  { ticker: "161390", name: "한국타이어앤테크놀로지", market: "KR" },
  { ticker: "034730", name: "SK",              market: "KR" },
  { ticker: "003550", name: "LG",              market: "KR" },
  { ticker: "000880", name: "한화",             market: "KR" },
  { ticker: "001040", name: "CJ",              market: "KR" },
  { ticker: "006260", name: "LS",              market: "KR" },
  { ticker: "028260", name: "삼성물산",          market: "KR" },
  { ticker: "267250", name: "HD현대",           market: "KR" },
  { ticker: "004800", name: "효성",             market: "KR" },
  { ticker: "005930", name: "삼성전자",          market: "KR" },
  { ticker: "000660", name: "SK하이닉스",        market: "KR" },
  { ticker: "035420", name: "NAVER",           market: "KR" },
  { ticker: "035720", name: "카카오",            market: "KR" },
  { ticker: "009150", name: "삼성전기",          market: "KR" },
  { ticker: "011070", name: "LG이노텍",         market: "KR" },
  { ticker: "282330", name: "BGF리테일",        market: "KR" },
  { ticker: "007070", name: "GS리테일",         market: "KR" },
  { ticker: "139480", name: "이마트",            market: "KR" },
  { ticker: "023530", name: "롯데쇼핑",          market: "KR" },
  { ticker: "097950", name: "CJ제일제당",        market: "KR" },
  { ticker: "001680", name: "대상",             market: "KR" },
  { ticker: "000080", name: "하이트진로",        market: "KR" },
  { ticker: "004170", name: "신세계",            market: "KR" },
  { ticker: "069960", name: "현대백화점",        market: "KR" },
  { ticker: "035250", name: "강원랜드",          market: "KR" },
  { ticker: "000720", name: "현대건설",          market: "KR" },
  { ticker: "047810", name: "한국항공우주",       market: "KR" },
  { ticker: "009540", name: "HD한국조선해양",     market: "KR" },
  { ticker: "042660", name: "한화오션",          market: "KR" },
  { ticker: "064350", name: "현대로템",          market: "KR" },
  { ticker: "000100", name: "유한양행",          market: "KR" },
  { ticker: "051910", name: "LG화학",           market: "KR" },
  { ticker: "006400", name: "삼성SDI",          market: "KR" },
  { ticker: "051900", name: "LG생활건강",        market: "KR" },
  { ticker: "003490", name: "대한항공",          market: "KR" },
];

export const US_TICKERS: TickerItem[] = [
  { ticker: "T",    name: "AT&T",                              market: "US" },
  { ticker: "VZ",   name: "Verizon",                           market: "US" },
  { ticker: "MO",   name: "Altria Group",                      market: "US" },
  { ticker: "PM",   name: "Philip Morris",                     market: "US" },
  { ticker: "BTI",  name: "British American Tobacco",          market: "US" },
  { ticker: "O",    name: "Realty Income",                     market: "US" },
  { ticker: "WPC",  name: "W. P. Carey",                       market: "US" },
  { ticker: "STAG", name: "STAG Industrial",                   market: "US" },
  { ticker: "NLY",  name: "Annaly Capital",                    market: "US" },
  { ticker: "AGNC", name: "AGNC Investment",                   market: "US" },
  { ticker: "JEPI", name: "JPMorgan Equity Premium Income ETF", market: "US" },
  { ticker: "JEPQ", name: "JPMorgan Nasdaq Equity Premium ETF", market: "US" },
  { ticker: "SCHD", name: "Schwab US Dividend ETF",            market: "US" },
  { ticker: "HDV",  name: "iShares Core High Dividend ETF",    market: "US" },
  { ticker: "SPYD", name: "SPDR S&P 500 High Dividend ETF",   market: "US" },
  { ticker: "VYM",  name: "Vanguard High Dividend Yield ETF",  market: "US" },
  { ticker: "QYLD", name: "Global X NASDAQ-100 Covered Call ETF", market: "US" },
  { ticker: "KO",   name: "Coca-Cola",                         market: "US" },
  { ticker: "PEP",  name: "PepsiCo",                           market: "US" },
  { ticker: "GIS",  name: "General Mills",                     market: "US" },
  { ticker: "MCD",  name: "McDonald's",                        market: "US" },
  { ticker: "TGT",  name: "Target",                            market: "US" },
  { ticker: "WMT",  name: "Walmart",                           market: "US" },
  { ticker: "JNJ",  name: "Johnson & Johnson",                 market: "US" },
  { ticker: "ABBV", name: "AbbVie",                            market: "US" },
  { ticker: "PFE",  name: "Pfizer",                            market: "US" },
  { ticker: "BMY",  name: "Bristol-Myers Squibb",              market: "US" },
  { ticker: "MRK",  name: "Merck",                             market: "US" },
  { ticker: "AMGN", name: "Amgen",                             market: "US" },
  { ticker: "IBM",  name: "IBM",                               market: "US" },
  { ticker: "INTC", name: "Intel",                             market: "US" },
  { ticker: "TXN",  name: "Texas Instruments",                 market: "US" },
  { ticker: "QCOM", name: "Qualcomm",                          market: "US" },
  { ticker: "AVGO", name: "Broadcom",                          market: "US" },
  { ticker: "XOM",  name: "ExxonMobil",                        market: "US" },
  { ticker: "CVX",  name: "Chevron",                           market: "US" },
  { ticker: "EPD",  name: "Enterprise Products Partners",      market: "US" },
  { ticker: "ET",   name: "Energy Transfer",                   market: "US" },
  { ticker: "ENB",  name: "Enbridge",                          market: "US" },
  { ticker: "MMM",  name: "3M",                                market: "US" },
  { ticker: "DOW",  name: "Dow Inc",                           market: "US" },
  { ticker: "CAT",  name: "Caterpillar",                       market: "US" },
  { ticker: "MAIN", name: "Main Street Capital",               market: "US" },
  { ticker: "ARCC", name: "Ares Capital",                      market: "US" },
  { ticker: "D",    name: "Dominion Energy",                   market: "US" },
  { ticker: "NEE",  name: "NextEra Energy",                    market: "US" },
  { ticker: "SO",   name: "Southern Company",                  market: "US" },
  { ticker: "DUK",  name: "Duke Energy",                       market: "US" },
  { ticker: "F",    name: "Ford Motor",                        market: "US" },
  { ticker: "AAPL", name: "Apple",                             market: "US" },
  { ticker: "MSFT", name: "Microsoft",                         market: "US" },
];

export function searchTickers(query: string, market: Market): TickerItem[] {
  if (!query.trim()) return [];
  const q = query.trim().toLowerCase();
  const list = market === "KR" ? KR_TICKERS : US_TICKERS;
  return list
    .filter(
      (t) =>
        t.name.toLowerCase().includes(q) ||
        t.ticker.toLowerCase().includes(q)
    )
    .slice(0, 20);
}
